<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-CE4M580C" ignored="0" name="First" tests="3" failures="1" timestamp="2022-04-18T22:50:22 IST" time="18.383" errors="0">
  <testcase name="loginWithDP" time="0.441" classname="test.TestClass"/>
  <testcase name="loginWithDP" time="0.434" classname="test.TestClass"/>
  <testcase name="loginWithDP" time="0.395" classname="test.TestClass">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at test.TestClass.loginWithDP(TestClass.java:49)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- loginWithDP -->
</testsuite> <!-- First -->
